### ISSUE TITLE
Elasticsearch refuses the connection

### ISSUE THREAD

**Issue by EduJGURJC** [elastest/elastest-data-manager#1] opened 2017-08-31 11:06 UTC
Hi,

I'm trying to start EDM with **docker-compose only and without rest-java component**, but Elasticsearch not working properly if I have not cloned the whole project, **refuses the connection**.

Is there any way to make it work without additional files?

Thanks in advance for the help.

**Comment by sgioldasis** [comment] 2017-08-31 12:59
Hi,

in order for us to be able to reproduce the issue could you please be more specific about what you are trying to do? Also, could you please provide some details of your environment (operating system, system resources etc) and a detailed list of the steps that you have performed that led to the problem? 

Thank you

**Comment by EduJGURJC** [comment] 2017-08-31 13:11
I'm using Ubuntu 16:04 64bits, 8GB RAM,  i7-3667U CPU @ 2.00GHz × 4, 250GB SSD

If I clone EDM project and execute docker-compose.yml, Elasticsearch works perfectly. 
The problem occurs when I just download docker-compose.yml and I run it. I have modified the docker-compose.yml to remove the rest-java component, since without the cloned project I can not build it.


Thank you

**Comment by sgioldasis** [comment] 2017-08-31 13:32
Hi again,

I suggest you try the following: Clone the project again from the latest master branch. We have made some modifications just today and it does not require to build rest-java anymore so you can use the docker-compose.yml without any modifications. 

I think this might solve your problem. If it doesn't we will investigate further.

Thank you

**Comment by EduJGURJC** [comment] 2017-08-31 13:36
Hi,

Cloning the project works perfectly but we want start up EDM without clone project, only with docker-compose.yml file.

Thank you

**Comment by sgioldasis** [comment] 2017-08-31 14:44
Hi,

although I don't quite understand your use case, I can think of two possible causes for the issue:

1. External file/folder dependencies. You will need the following files/folders from the project: 
./elasticsearch/config/elasticsearch.yml
./elasticsearch/esdata1
./elasticsearch/esdata2
./backup/elasticsearch

2. Host system setup: You will need to execute the following command in your Ubuntu system (before you start the docker-compose)

sudo sysctl -w vm.max_map_count=262144

Then you should check if vm.max_map_count is set using the following command
sysctl vm.max_map_count
(should output 262144 in your console)

Please let me know if the above solve your issue.

Thank you

**Comment by sgioldasis** [comment] 2017-09-11 09:40
Closing the issue since 11 days passed without any activity.

**Closed by sgioldasis** 2017-09-11 09:40 UTC
